# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SNWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sampling(object):
    def setupUi(self, Sampling):
        Sampling.setObjectName("Sampling")
        Sampling.resize(291, 341)
        Sampling.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Sampling)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 2)
        Sampling.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sampling)
        QtCore.QMetaObject.connectSlotsByName(Sampling)

    def retranslateUi(self, Sampling):
        _translate = QtCore.QCoreApplication.translate
        Sampling.setWindowTitle(_translate("Sampling", "Sampling Network"))
        self.label.setText(_translate("Sampling", "Sampling Rate"))
        self.label_2.setText(_translate("Sampling", "Data Collect"))
        self.comboBox.setItemText(0, _translate("Sampling", "1 HZ"))
        self.comboBox.setItemText(1, _translate("Sampling", "2 HZ"))
        self.comboBox.setItemText(2, _translate("Sampling", "4 HZ"))
        self.comboBox.setItemText(3, _translate("Sampling", "8 HZ"))
        self.comboBox.setItemText(4, _translate("Sampling", "16 HZ"))
        self.comboBox.setItemText(5, _translate("Sampling", "32 HZ"))
        self.comboBox.setItemText(6, _translate("Sampling", "64 HZ"))
        self.comboBox.setItemText(7, _translate("Sampling", "128 HZ"))
        self.comboBox.setItemText(8, _translate("Sampling", "256 HZ"))
        self.comboBox.setItemText(9, _translate("Sampling", "512 HZ"))
        self.comboBox_2.setItemText(0, _translate("Sampling", "Log and Transmit"))
        self.comboBox_2.setItemText(1, _translate("Sampling", "Log Only"))
        self.comboBox_2.setItemText(2, _translate("Sampling", "Transmit Only"))
        self.pushButton_2.setText(_translate("Sampling", "Cancel"))
        self.pushButton.setText(_translate("Sampling", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sampling = QtWidgets.QMainWindow()
    ui = Ui_Sampling()
    ui.setupUi(Sampling)
    Sampling.show()
    sys.exit(app.exec_())
